_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: YouTube Downloader
homepageEnabled: true
homepageGroup: Media
homepageIcon: metube
homepageName: MeTube
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: metube.crt.house
ingName: metube
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: 'app: metube'
name: metube
namespace: metube
pvc: false
reloader: true
resources:
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- services.yaml
service: true
serviceAccount: false
svcName: metube
svcPortName: metube
svcPortNum: 8081
svcProtocol: TCP
svcSelector: 'app: metube'
svcTargetPort: metube
svcType: ClusterIP
upstreamURL: https://github.com/alexta69/metube
url: https://github.com/charlesthomas/homelab-metube
