---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metube

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-metube
commonLabels:
  app: metube

resources:
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: metube
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
