---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cookies
  namespace: metube
spec:
  target:
    name: cookies
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        cookies.txt: |-
          {{ .cookies }}
  data:
    - secretKey: cookies
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: metube-cookies
        metadataPolicy: None
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
