---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyfin
  namespace: metube
spec:
  target:
    name: jellyfin
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: c7c29fcf-cd4c-4e42-984a-b09a5a1157ef
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
